### ISSUE TITLE
Earthsdk.js报错

### ISSUE THREAD

**Issue by Phoenix1x** [YongMaple/vue3.0-vue-cli3-earthsdk#1]
在vue项目里用组件方式写的,改了main.js,然后创建vue实例的时候用的earthsdk官方给的方式
`// 修改后的代码
function startup() {
  new Vue({
    render: h => h(App),
  }).$mount('#app')
}
// 1 XE.ready()会加载Cesium.js等其他资源，注意ready()返回一个Promise对象。
XE.ready().then(startup);`
但是运行的时候earthsdk.js会报错,地球完全黑的但是确实有,bim模型转的3dtiles加载后又能看到
transferTypedArrayTest.js:1和cesiumWorkerBootstrapper.js:1都报Uncaught SyntaxError: Unexpected token '<'这个错

**Comment by YongMaple** [comment]
已经提示你"<"错误了，检查一下吧，看不到你具体代码，只能猜测了
